name: "🚀 publish to npm"

on:
    push:
        branches:
          - master

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-18.04
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2
            - name: 🟢 node
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: https://registry.npmjs.org
            - name: 📦 install
              run: npm install
            - name: 🧪 test
              run: npm run test:ci
            - name: 🔧 build
              run: npm run build
            - name: 🚀 publish              
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}